version: '3.8'
services:
  app:
    image: php:8.2-fpm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: theme_manager
    ports:
      - "3306:3306"
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
